import React, { createContext, useContext, useEffect, useMemo, useState } from "react"

export const LANGUAGE_OPTIONS = [
  { value:'fr', label:'Français', short:'FR', locale:'fr-FR' },
  { value:'en', label:'English', short:'EN', locale:'en-US' },
  { value:'mg', label:'Malagasy', short:'MG', locale:'mg-MG' },
]

const translations = {
  fr: {
    'nav.dashboard':'Tableau de bord',
    'nav.patients':'Patients',
    'nav.appointments':'Rendez-vous',
    'nav.quotes':'Devis',
    'nav.invoices':'Factures',
    'nav.purchases':'Achats',
    'nav.suppliers':'Fournisseurs',
    'nav.lab':'Laboratoire',
    'nav.reports':'Rapports',
    'nav.inventory':'Stock',
    'nav.inventoryLong':'Stock et inventaire',
    'nav.mailing':'Mailing',
    'nav.settings':'Paramètres',
    'nav.cabinetSettings':'Paramètres cabinet',
    'nav.pricing':'Tarifs des actes',
    'nav.subscription':'Abonnement',
    'nav.mySubscription':'Mon Abonnement',
    'nav.revenueDashboard':'Dashboard revenus',
    'nav.clinics':'Cabinets abonnés',
    'nav.paymentValidation':'Validation paiements',
    'nav.partners':'Fournisseurs partenaires',
    'nav.payments':'Paiements',
    'nav.dentalpm':'DentalPM',
    'group.actions':'Actions',
    'group.modules':'Modules',
    'group.admin':'Administration',
    'quick.patient.desc':'Ouvrir le registre patient',
    'quick.appointment.desc':'Agenda et disponibilités',
    'quick.invoice.desc':'Facturation cabinet',
    'quick.quote.desc':'Devis et conversion facture',
    'quick.inventory.desc':'Produits, seuils et mouvements',
    'quick.purchases.desc':'Dépenses cabinet et médicaments',
    'quick.reports.desc':'Chiffres, revenus et dépenses',
    'quick.lab.desc':'Commandes prothèses et statuts',
    'quick.suppliers.desc':'Carnet fournisseurs',
    'quick.mailing.desc':'Messages et relances patient',
    'quick.subscription.desc':'Plan et facturation SaaS',
    'quick.settings.desc':'Profil, équipe et configuration',
    'role.superAdmin':'Super Admin',
    'role.admin':'Administrateur',
    'role.dentist':'Dentiste',
    'role.assistant':'Assistante',
    'role.accountant':'Comptable',
    'label.administration':'Administration',
    'label.platformAdmin':'Administration plateforme',
    'label.dentalClinic':'Cabinet dentaire',
    'label.navigation':'Navigation',
    'label.trialPlan':'{plan} — Essai',
    'label.availableIn':'Disponible en {plan}',
    'label.upgradePlan':'Upgrader mon plan',
    'label.subscription':'Abonnement',
    'label.status':'Statut: {status}',
    'label.user':'Utilisateur',
    'label.superAdministrator':'Super Administrateur',
    'label.defaultClinic':'Cabinet DentalPM',
    'topbar.newAppointment':'Nouveau RDV',
    'topbar.online':'Synchro active',
    'topbar.offline':'Hors ligne',
    'topbar.timezone':'Madagascar',
    'topbar.searchPlaceholder':'Rechercher patients, factures...',
    'topbar.language':'Langue de l’interface',
    'notifications.title':'Notifications',
    'notifications.markAllRead':'Tout marquer lu',
    'notifications.follow.title':'Suivi du jour',
    'notifications.follow.text':'Vérifiez les rendez-vous et les factures en attente.',
    'notifications.finance.title':'Finance',
    'notifications.finance.text':'Ouvrir les rapports pour contrôler recettes et dépenses.',
    'profile.myProfile':'Mon profil',
    'profile.settings':'Paramètres',
    'profile.logout':'Se déconnecter',
    'command.empty':'Aucun raccourci trouvé',
    'command.enter':'Entrée pour ouvrir',
    'command.escape':'Échap pour fermer',
  },
  en: {
    'nav.dashboard':'Dashboard',
    'nav.patients':'Patients',
    'nav.appointments':'Appointments',
    'nav.quotes':'Quotes',
    'nav.invoices':'Invoices',
    'nav.purchases':'Purchases',
    'nav.suppliers':'Suppliers',
    'nav.lab':'Laboratory',
    'nav.reports':'Reports',
    'nav.inventory':'Inventory',
    'nav.inventoryLong':'Inventory and stock',
    'nav.mailing':'Mailing',
    'nav.settings':'Settings',
    'nav.cabinetSettings':'Clinic settings',
    'nav.pricing':'Procedure fees',
    'nav.subscription':'Subscription',
    'nav.mySubscription':'My subscription',
    'nav.revenueDashboard':'Revenue dashboard',
    'nav.clinics':'Subscribed clinics',
    'nav.paymentValidation':'Payment validation',
    'nav.partners':'Partner suppliers',
    'nav.payments':'Payments',
    'nav.dentalpm':'DentalPM',
    'group.actions':'Actions',
    'group.modules':'Modules',
    'group.admin':'Administration',
    'quick.patient.desc':'Open the patient registry',
    'quick.appointment.desc':'Schedule and availability',
    'quick.invoice.desc':'Clinic billing',
    'quick.quote.desc':'Quotes and invoice conversion',
    'quick.inventory.desc':'Products, thresholds and movements',
    'quick.purchases.desc':'Clinic expenses and medicines',
    'quick.reports.desc':'Figures, revenue and expenses',
    'quick.lab.desc':'Prosthesis orders and statuses',
    'quick.suppliers.desc':'Supplier directory',
    'quick.mailing.desc':'Patient messages and reminders',
    'quick.subscription.desc':'Plan and SaaS billing',
    'quick.settings.desc':'Profile, team and configuration',
    'role.superAdmin':'Super Admin',
    'role.admin':'Administrator',
    'role.dentist':'Dentist',
    'role.assistant':'Assistant',
    'role.accountant':'Accountant',
    'label.administration':'Administration',
    'label.platformAdmin':'Platform administration',
    'label.dentalClinic':'Dental clinic',
    'label.navigation':'Navigation',
    'label.trialPlan':'{plan} — Trial',
    'label.availableIn':'Available in {plan}',
    'label.upgradePlan':'Upgrade my plan',
    'label.subscription':'Subscription',
    'label.status':'Status: {status}',
    'label.user':'User',
    'label.superAdministrator':'Super Administrator',
    'label.defaultClinic':'DentalPM Clinic',
    'topbar.newAppointment':'New appointment',
    'topbar.online':'Sync active',
    'topbar.offline':'Offline',
    'topbar.timezone':'Madagascar',
    'topbar.searchPlaceholder':'Search patients, invoices...',
    'topbar.language':'Interface language',
    'notifications.title':'Notifications',
    'notifications.markAllRead':'Mark all read',
    'notifications.follow.title':'Today’s follow-up',
    'notifications.follow.text':'Check pending appointments and invoices.',
    'notifications.finance.title':'Finance',
    'notifications.finance.text':'Open reports to review revenue and expenses.',
    'profile.myProfile':'My profile',
    'profile.settings':'Settings',
    'profile.logout':'Log out',
    'command.empty':'No shortcut found',
    'command.enter':'Enter to open',
    'command.escape':'Esc to close',
  },
  mg: {
    'nav.dashboard':'Tabilao',
    'nav.patients':'Marary',
    'nav.appointments':'Fotoana',
    'nav.quotes':'Tombam-bidy',
    'nav.invoices':'Faktiora',
    'nav.purchases':'Fividianana',
    'nav.suppliers':'Mpamatsy',
    'nav.lab':'Laboratoara',
    'nav.reports':'Tatitra',
    'nav.inventory':'Tahiry',
    'nav.inventoryLong':'Tahiry sy entana',
    'nav.mailing':'Mailing',
    'nav.settings':'Fikirana',
    'nav.cabinetSettings':'Fikirana kabinetra',
    'nav.pricing':"Saran'asa",
    'nav.subscription':'Famandrihana',
    'nav.mySubscription':'Famandrihako',
    'nav.revenueDashboard':'Tabilao vola miditra',
    'nav.clinics':'Kabinetra misoratra',
    'nav.paymentValidation':'Fanamarinana fandoavana',
    'nav.partners':'Mpamatsy mpiara-miasa',
    'nav.payments':'Fandoavana',
    'nav.dentalpm':'DentalPM',
    'group.actions':'Asa',
    'group.modules':'Modules',
    'group.admin':'Fitantanana',
    'quick.patient.desc':'Sokafy ny rejisitry ny marary',
    'quick.appointment.desc':'Kalandrie sy fahafahana',
    'quick.invoice.desc':'Faktioran’ny kabinetra',
    'quick.quote.desc':'Tombam-bidy sy fanovana ho faktiora',
    'quick.inventory.desc':'Entana, fetra ary fivezivezena',
    'quick.purchases.desc':'Lany amin’ny kabinetra sy fanafody',
    'quick.reports.desc':'Isa, vola miditra ary lany',
    'quick.lab.desc':'Kaomandy protheses sy satan’izy ireo',
    'quick.suppliers.desc':'Lisitr’ireo mpamatsy',
    'quick.mailing.desc':'Hafatra sy fampahatsiahivana marary',
    'quick.subscription.desc':'Drafitra sy faktioran’ny SaaS',
    'quick.settings.desc':'Profil, ekipa ary fikirana',
    'role.superAdmin':'Super Admin',
    'role.admin':'Mpitantana',
    'role.dentist':'Dokotera nify',
    'role.assistant':'Mpanampy',
    'role.accountant':'Mpitantana kaonty',
    'label.administration':'Fitantanana',
    'label.platformAdmin':'Fitantanana sehatra',
    'label.dentalClinic':'Kabinetra nify',
    'label.navigation':'Fitetezana',
    'label.trialPlan':'{plan} — Fitsapana',
    'label.availableIn':'Misy amin’ny {plan}',
    'label.upgradePlan':'Hanavao ny planiko',
    'label.subscription':'Famandrihana',
    'label.status':'Sata: {status}',
    'label.user':'Mpampiasa',
    'label.superAdministrator':'Super Administrateur',
    'label.defaultClinic':'Kabinetra DentalPM',
    'topbar.newAppointment':'Fotoana vaovao',
    'topbar.online':'Miasa ny sync',
    'topbar.offline':'Tsy an-tserasera',
    'topbar.timezone':'Madagasikara',
    'topbar.searchPlaceholder':'Hikaroka marary, faktiora...',
    'topbar.language':'Fitenin’ny interface',
    'notifications.title':'Fampandrenesana',
    'notifications.markAllRead':'Mariho fa voavaky',
    'notifications.follow.title':'Fanarahana androany',
    'notifications.follow.text':'Jereo ny fotoana sy faktiora mbola miandry.',
    'notifications.finance.title':'Vola',
    'notifications.finance.text':'Sokafy ny tatitra hijerena vola miditra sy lany.',
    'profile.myProfile':'Profiliko',
    'profile.settings':'Fikirana',
    'profile.logout':'Hivoaka',
    'command.empty':'Tsy misy shortcut hita',
    'command.enter':'Enter hanokafana',
    'command.escape':'Esc hanakatonana',
  },
}

const LanguageContext = createContext({
  language: 'fr',
  setLanguage: () => {},
  locale: 'fr-FR',
  options: LANGUAGE_OPTIONS,
  t: key => key,
})

export function LanguageProvider({ children, defaultLanguage = 'fr', storageKey = 'dpm_language' }) {
  const [language, setLanguageState] = useState(() => {
    try { return localStorage.getItem(storageKey) || defaultLanguage } catch { return defaultLanguage }
  })

  const safeLanguage = translations[language] ? language : defaultLanguage
  const locale = LANGUAGE_OPTIONS.find(option => option.value === safeLanguage)?.locale || 'fr-FR'

  useEffect(() => {
    document.documentElement.lang = safeLanguage
    try { localStorage.setItem(storageKey, safeLanguage) } catch {}
    window.dispatchEvent(new CustomEvent('dpm:language-change', { detail: { language: safeLanguage } }))
  }, [safeLanguage, storageKey])

  const t = useMemo(() => (key, values = {}) => {
    const template = translations[safeLanguage]?.[key] || translations.fr[key] || key
    return Object.entries(values).reduce(
      (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
      template
    )
  }, [safeLanguage])

  const value = useMemo(() => ({
    language: safeLanguage,
    setLanguage: setLanguageState,
    locale,
    options: LANGUAGE_OPTIONS,
    t,
  }), [safeLanguage, locale, t])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
